// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qlgxkU4iP6K64jqJWTZLzCw8Bi2Md0A',
    appId: '1:94876127409:web:ccdd07d9773c0025f2d290',
    messagingSenderId: '94876127409',
    projectId: 'testeflutter-e1c1b',
    authDomain: 'testeflutter-e1c1b.firebaseapp.com',
    storageBucket: 'testeflutter-e1c1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMfYmdEbZMgLslIGQctTuWIOX2K4rWzM',
    appId: '1:94876127409:android:a1a0980ec5ace6aff2d290',
    messagingSenderId: '94876127409',
    projectId: 'testeflutter-e1c1b',
    storageBucket: 'testeflutter-e1c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2d-gxXCtnw9iX9t_8niotf0fP23KMg4s',
    appId: '1:94876127409:ios:c168065780951e68f2d290',
    messagingSenderId: '94876127409',
    projectId: 'testeflutter-e1c1b',
    storageBucket: 'testeflutter-e1c1b.firebasestorage.app',
    iosBundleId: 'com.example.testeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2d-gxXCtnw9iX9t_8niotf0fP23KMg4s',
    appId: '1:94876127409:ios:c168065780951e68f2d290',
    messagingSenderId: '94876127409',
    projectId: 'testeflutter-e1c1b',
    storageBucket: 'testeflutter-e1c1b.firebasestorage.app',
    iosBundleId: 'com.example.testeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9qlgxkU4iP6K64jqJWTZLzCw8Bi2Md0A',
    appId: '1:94876127409:web:0c6cb544d15c17c5f2d290',
    messagingSenderId: '94876127409',
    projectId: 'testeflutter-e1c1b',
    authDomain: 'testeflutter-e1c1b.firebaseapp.com',
    storageBucket: 'testeflutter-e1c1b.firebasestorage.app',
  );
}
